'use strict';function u(f,a,b,d){f.v.sc(f.bb,a,b,d,void 0)}function D(f,a,b,d){f.v.ca?u(f,a,b,d):f.v.mf()._OnMessageFromDOM({type:"event",component:f.bb,handler:a,dispatchOpts:d||null,data:b,responseId:null})}function G(f,a,b){f.v.C(f.bb,a,b)}function I(f,a){for(const [b,d]of a)G(f,b,d)}function J(f){f.Tb||(f.v.Xe(f.he),f.Tb=!0)}window.sa=class{constructor(f,a){this.v=f;this.bb=a;this.Tb=!1;this.he=()=>this.va()}ld(){}va(){}};function K(f){-1!==f.Sa&&(self.clearTimeout(f.Sa),f.Sa=-1)}
window.Oe=class{constructor(f,a){this.Rc=f;this.Fg=a;this.Sa=-1;this.Ub=-Infinity;this.ie=()=>{this.Sa=-1;this.Ub=Date.now();this.hb=!0;this.Rc();this.hb=!1};this.Qd=this.hb=!1}c(){K(this);this.ie=this.Rc=null}};"use strict";function N(f,a){G(f,"get-element",b=>{const d=f.ba.get(b.elementId);return a(d,b)})}
window.$g=class extends self.sa{constructor(f,a){super(f,a);this.ba=new Map;this.Qc=!0;I(this,[["create",()=>{throw Error("required override");}],["destroy",b=>{{b=b.elementId;const d=this.ba.get(b);this.Qc&&d.parentElement.removeChild(d);this.ba.delete(b)}}],["set-visible",b=>{this.Qc&&(this.ba.get(b.elementId).style.display=b.isVisible?"":"none")}],["update-position",b=>{if(this.Qc){var d=this.ba.get(b.elementId);d.style.left=b.left+"px";d.style.top=b.top+"px";d.style.width=b.width+"px";d.style.height=
b.height+"px";b=b.fontSize;null!==b&&(d.style.fontSize=b+"em")}}],["update-state",b=>{this.ba.get(b.elementId);throw Error("required override");}],["focus",b=>this.Kc(b)],["set-css-style",b=>{this.ba.get(b.elementId).style[b.prop]=b.val}],["set-attribute",b=>{this.ba.get(b.elementId).setAttribute(b.name,b.val)}],["remove-attribute",b=>{this.ba.get(b.elementId).removeAttribute(b.name)}]]);N(this,b=>b)}Kc(f){var a=this.ba.get(f.elementId);f.focus?a.focus():a.blur()}};"use strict";
{const f=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent);let a=0;function b(g){const c=document.createElement("script");c.async=!1;c.type="module";return g.Qg?new Promise(k=>{const l="c3_resolve_"+a;++a;self[l]=k;c.textContent=g.Ug+`\n\nself["${l}"]();`;document.head.appendChild(c)}):new Promise((k,l)=>{c.onload=k;c.onerror=l;c.src=g;document.head.appendChild(c)})}let d=!1,h=!1;function m(){if(!d){try{new Worker("blob://",{get type(){h=!0}})}catch(g){}d=!0}return h}let p=
new Audio;const x={"audio/webm; codecs=opus":!!p.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!p.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!p.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!p.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!p.canPlayType("audio/mp4"),"audio/mpeg":!!p.canPlayType("audio/mpeg")};p=null;async function A(g){g=await B(g);return(new TextDecoder("utf-8")).decode(g)}function B(g){return new Promise((c,
k)=>{const l=new FileReader;l.onload=n=>c(n.target.result);l.onerror=n=>k(n);l.readAsArrayBuffer(g)})}const v=[];let w=0;window.RealFile=window.File;const C=[],H=new Map,z=new Map;let L=0;const E=[];self.runOnStartup=function(g){if("function"!==typeof g)throw Error("runOnStartup called without a function");E.push(g)};const M=new Set(["cordova","playable-ad","instant-games"]);let e=!1;window.fa=class g{constructor(c){this.ca=c.Wg;this.pa=null;this.F="";this.fc=c.Tg;this.wb={};this.La=this.vb=null;
this.Rb=[];this.kb=this.G=this.Qa=null;this.Pa=-1;this.Kg=()=>this.Of();this.Oa=[];this.s=c.je;this.ib="file"===location.protocol.substr(0,4);!this.ca||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&m()||(this.ca=!1);if("playable-ad"===this.s||"instant-games"===this.s)this.ca=!1;if("cordova"===this.s&&this.ca)if(/android/i.test(navigator.userAgent)){const k=/Chrome\/(\d+)/i.exec(navigator.userAgent);k&&90<=parseInt(k[1],10)||(this.ca=!1)}else this.ca=!1;this.Wb=this.ia=null;"html5"!==
this.s&&"playable-ad"!==this.s||!this.ib||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");"html5"!==this.s||window.isSecureContext||console.warn("[Construct 3] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.C("runtime","cordova-fetch-local-file",k=>this.uf(k));this.C("runtime",
"create-job-worker",()=>this.vf());"cordova"===this.s?document.addEventListener("deviceready",()=>this.Dd(c)):this.Dd(c)}c(){this.yc();this.pa&&(this.pa=this.pa.onmessage=null);this.vb&&(this.vb.terminate(),this.vb=null);this.La&&(this.La.c(),this.La=null);this.G&&(this.G.parentElement.removeChild(this.G),this.G=null)}Je(){return f&&"cordova"===this.s}rc(){const c=navigator.userAgent;return f&&M.has(this.s)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(c)}async Dd(c){"macos-wkwebview"===
this.s&&this.Oc({type:"ready"});if("playable-ad"===this.s){this.ia=self.c3_base64files;this.Wb={};await this.bf();for(let l=0,n=c.Ta.length;l<n;++l){var k=c.Ta[l].toLowerCase();this.Wb.hasOwnProperty(k)?c.Ta[l]={Qg:!0,Ug:this.Wb[k]}:this.ia.hasOwnProperty(k)&&(c.Ta[l]=URL.createObjectURL(this.ia[k]))}}c.Lg?this.F=c.Lg:(k=location.origin,this.F=("null"===k?"file:///":k)+location.pathname,k=this.F.lastIndexOf("/"),-1!==k&&(this.F=this.F.substr(0,k+1)));c.Yg&&(this.wb=c.Yg);k=new MessageChannel;this.pa=
k.port1;this.pa.onmessage=l=>this._OnMessageFromRuntime(l.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(l=>this.Kf(l));this.kb=new self.Ke(this);await O(this.kb);"object"===typeof window.StatusBar&&window.StatusBar.hide();"object"===typeof window.AndroidFullScreen&&window.AndroidFullScreen.immersiveMode();this.ca?await this.pf(c,k.port2):await this.nf(c,k.port2)}Bc(c){c=this.wb.hasOwnProperty(c)?this.wb[c]:c.endsWith("/workermain.js")&&this.wb.hasOwnProperty("workermain.js")?
this.wb["workermain.js"]:"playable-ad"===this.s&&this.ia.hasOwnProperty(c.toLowerCase())?this.ia[c.toLowerCase()]:c;c instanceof Blob&&(c=URL.createObjectURL(c));return c}async lc(c,k,l){if(c.startsWith("blob:"))return new Worker(c,l);if("cordova"===this.s&&this.ib)return c=await this.xb(l.Pg?c:this.fc+c),new Worker(URL.createObjectURL(new Blob([c],{type:"application/javascript"})),l);c=new URL(c,k);if(location.origin!==c.origin){c=await fetch(c);if(!c.ok)throw Error("failed to fetch worker script");
c=await c.blob();return new Worker(URL.createObjectURL(c),l)}return new Worker(c,l)}ya(){return Math.max(window.innerWidth,1)}xa(){return Math.max(window.innerHeight,1)}Bd(c){var k=this.kb;return{baseUrl:this.F,windowInnerWidth:this.ya(),windowInnerHeight:this.xa(),devicePixelRatio:window.devicePixelRatio,isFullscreen:g.Wa(),projectData:c.fh,previewImageBlobs:window.cr_previewImageBlobs||this.ia,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,previewProjectFileSWUrls:window.cr_previewProjectFiles,
swClientId:window.dh||"",exportType:c.je,isDebug:-1<self.location.search.indexOf("debug"),ife:!!self.eh,jobScheduler:{inputPort:k.Xc,outputPort:k.dd,maxNumWorkers:k.Hg},supportedAudioFormats:x,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.fc+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.fc+"opus.wasm.wasm",isFileProtocol:this.ib,isiOSCordova:this.Je(),isiOSWebView:this.rc(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async pf(c,k){var l=this.Bc(c.Xg);this.vb=
await this.lc(l,this.F,{type:"module",name:"Runtime",Pg:!0});this.G=document.createElement("canvas");this.G.style.display="none";l=this.G.transferControlToOffscreen();document.body.appendChild(this.G);window.c3canvas=this.G;let n=c.kd||[],t=c.Ta;n=await Promise.all(n.map(q=>this.Ga(q)));t=await Promise.all(t.map(q=>this.Ga(q)));if("cordova"===this.s)for(let q=0,r=c.jc.length;q<r;++q){const y=c.jc[q],F=y[0];if(F===c.hd||"scriptsInEvents.js"===F||F.endsWith("/scriptsInEvents.js"))y[1]=await this.Ga(F)}this.vb.postMessage(Object.assign(this.Bd(c),
{type:"init-runtime",isInWorker:!0,messagePort:k,canvas:l,workerDependencyScripts:n,engineScripts:t,projectScripts:c.jc,mainProjectScript:c.hd,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[k,l,...P(this.kb)]);this.Rb=C.map(q=>new q(this));this.Ad();self.c3_callFunction=(q,r)=>this.Qa.qf(q,r);"preview"===this.s&&(self.goToLastErrorScript=()=>this.sc("runtime","go-to-last-error-script"))}async nf(c,k){this.G=document.createElement("canvas");this.G.style.display="none";document.body.appendChild(this.G);
window.c3canvas=this.G;this.Rb=C.map(q=>new q(this));this.Ad();var l=c.Ta.map(q=>"string"===typeof q?(new URL(q,this.F)).toString():q);Array.isArray(c.kd)&&l.unshift(...c.kd);l=await Promise.all(l.map(q=>this.Ga(q)));await Promise.all(l.map(q=>b(q)));l=self.C3_ProjectScriptsStatus;const n=c.hd,t=c.jc;for(let [q,r]of t)if(r||(r=q),q===n)try{r=await this.Ga(r),await b(r),"preview"!==this.s||l[q]||this.Ld(q,"main script did not run to completion")}catch(y){this.Ld(q,y)}else if("scriptsInEvents.js"===
q||q.endsWith("/scriptsInEvents.js"))r=await this.Ga(r),await b(r);"preview"===this.s&&"object"!==typeof self.Zg.ah?(this.Kb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(c=Object.assign(this.Bd(c),{isInWorker:!1,messagePort:k,canvas:this.G,runOnStartupFunctions:E}),this.Fd(),this.La=self.C3_CreateRuntime(c),await self.C3_InitRuntime(this.La,
c))}Ld(c,k){this.Kb();console.error(`[Preview] Failed to load project main script (${c}): `,k);alert(`Failed to load project main script (${c}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Fd(){this.Kb()}Kb(){const c=window.Mg;c&&(c.parentElement.removeChild(c),window.Mg=null)}async vf(){const c=await Q(this.kb);return{outputPort:c,transferables:[c]}}mf(){if(this.ca)throw Error("not available in worker mode");return this.La}sc(c,k,l,n,t){this.pa.postMessage({type:"event",
component:c,handler:k,dispatchOpts:n||null,data:l,responseId:null},t)}td(c,k,l,n,t){const q=L++,r=new Promise((y,F)=>{z.set(q,{resolve:y,reject:F})});this.pa.postMessage({type:"event",component:c,handler:k,dispatchOpts:n||null,data:l,responseId:q},t);return r}["_OnMessageFromRuntime"](c){const k=c.type;if("event"===k)return this.Af(c);if("result"===k)this.Sf(c);else if("runtime-ready"===k)this.Tf();else if("alert-error"===k)this.Kb(),alert(c.message);else if("creating-runtime"===k)this.Fd();else throw Error(`unknown message '${k}'`);
}Af(c){const k=c.component,l=c.handler,n=c.data,t=c.responseId;if(c=H.get(k))if(c=c.get(l)){var q=null;try{q=c(n)}catch(r){console.error(`Exception in '${k}' handler '${l}':`,r);null!==t&&this.Jb(t,!1,""+r);return}if(null===t)return q;q&&q.then?q.then(r=>this.Jb(t,!0,r)).catch(r=>{console.error(`Rejection from '${k}' handler '${l}':`,r);this.Jb(t,!1,""+r)}):this.Jb(t,!0,q)}else console.warn(`[DOM] No handler '${l}' for component '${k}'`);else console.warn(`[DOM] No event handlers for component '${k}'`)}Jb(c,
k,l){let n;l&&l.transferables&&(n=l.transferables);this.pa.postMessage({type:"result",responseId:c,isOk:k,result:l},n)}Sf(c){const k=c.responseId,l=c.isOk;c=c.result;const n=z.get(k);l?n.resolve(c):n.reject(c);z.delete(k)}C(c,k,l){let n=H.get(c);n||(n=new Map,H.set(c,n));if(n.has(k))throw Error(`[DOM] Component '${c}' already has handler '${k}'`);n.set(k,l)}static Da(c){if(C.includes(c))throw Error("DOM handler already added");C.push(c)}Ad(){for(const c of this.Rb)if("runtime"===c.bb){this.Qa=c;return}throw Error("cannot find runtime DOM handler");
}Kf(c){this.sc("debugger","message",c)}Tf(){for(const c of this.Rb)c.ld()}static Wa(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||e)}static Lb(c){e=!!c}Xe(c){this.Oa.push(c);this.Nc()}fg(c){c=this.Oa.indexOf(c);if(-1===c)throw Error("invalid callback");this.Oa.splice(c,1);this.Oa.length||this.yc()}Nc(){-1===this.Pa&&this.Oa.length&&(this.Pa=requestAnimationFrame(this.Kg))}yc(){-1!==this.Pa&&(cancelAnimationFrame(this.Pa),this.Pa=-1)}Of(){this.Pa=
-1;for(const c of this.Oa)c();this.Nc()}wa(c){this.Qa.wa(c)}Fa(c){this.Qa.Fa(c)}Mc(){this.Qa.Mc()}Db(c){this.Qa.Db(c)}Ie(){return!!x["audio/webm; codecs=opus"]}async Dg(c){c=await this.td("runtime","opus-decode",{arrayBuffer:c},null,[c]);return new Float32Array(c)}He(c){return/^(?:[a-z\-]+:)?\/\//.test(c)||"data:"===c.substr(0,5)||"blob:"===c.substr(0,5)}sd(c){return!this.He(c)}async Ga(c){return"cordova"===this.s&&(c.startsWith("file:")||this.ib&&this.sd(c))?(c.startsWith(this.F)&&(c=c.substr(this.F.length)),
c=await this.xb(c),URL.createObjectURL(new Blob([c],{type:"application/javascript"}))):c}async uf(c){const k=c.filename;switch(c.as){case "text":return await this.Ae(k);case "buffer":return await this.xb(k);default:throw Error("unsupported type");}}od(c){const k=window.cordova.file.applicationDirectory+"www/"+c.toLowerCase();return new Promise((l,n)=>{window.resolveLocalFileSystemURL(k,t=>{t.file(l,n)},n)})}async Ae(c){c=await this.od(c);return await A(c)}zc(){if(v.length&&!(8<=w)){w++;var c=v.shift();
this.cf(c.filename,c.Vg,c.Og)}}xb(c){return new Promise((k,l)=>{v.push({filename:c,Vg:n=>{w--;this.zc();k(n)},Og:n=>{w--;this.zc();l(n)}});this.zc()})}async cf(c,k,l){try{const n=await this.od(c),t=await B(n);k(t)}catch(n){l(n)}}Oc(c){if("windows-webview2"===this.s)window.chrome.webview.postMessage(JSON.stringify(c));else if("macos-wkwebview"===this.s)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(c));else throw Error("cannot send wrapper message");}async bf(){const c=[];for(const [k,
l]of Object.entries(this.ia))c.push(this.af(k,l));await Promise.all(c)}async af(c,k){if("object"===typeof k)this.ia[c]=new Blob([k.str],{type:k.type}),this.Wb[c]=k.str;else{let l=await this.kf(k);l||(l=this.ef(k));this.ia[c]=l}}async kf(c){try{return await (await fetch(c)).blob()}catch(k){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
k),null}}ef(c){c=this.$f(c);return this.$e(c.data,c.Rg)}$f(c){var k=c.indexOf(",");if(0>k)throw new URIError("expected comma in data: uri");var l=c.substring(k+1);k=c.substring(5,k).split(";");c=k[0]||"";const n=k[2];l="base64"===k[1]||"base64"===n?atob(l):decodeURIComponent(l);return{Rg:c,data:l}}$e(c,k){var l=c.length;let n=l>>2,t=new Uint8Array(l),q=new Uint32Array(t.buffer,0,n),r,y;for(y=r=0;r<n;++r)q[r]=c.charCodeAt(y++)|c.charCodeAt(y++)<<8|c.charCodeAt(y++)<<16|c.charCodeAt(y++)<<24;for(l&=
3;l--;)t[y]=c.charCodeAt(y),++y;return new Blob([t],{type:k})}}}"use strict";
{const f=self.fa;function a(e){return e.sourceCapabilities&&e.sourceCapabilities.firesTouchEvents||e.originalEvent&&e.originalEvent.sourceCapabilities&&e.originalEvent.sourceCapabilities.firesTouchEvents}const b=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),d={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},h={dispatchUserScriptEvent:!0},m={dispatchRuntimeEvent:!0};function p(e){return new Promise((g,c)=>{const k=document.createElement("link");k.onload=()=>g(k);k.onerror=l=>c(l);k.rel=
"stylesheet";k.href=e;document.head.appendChild(k)})}function x(e){return new Promise((g,c)=>{const k=new Image;k.onload=()=>g(k);k.onerror=l=>c(l);k.src=e})}async function A(e){e=URL.createObjectURL(e);try{return await x(e)}finally{URL.revokeObjectURL(e)}}function B(e){return new Promise((g,c)=>{let k=new FileReader;k.onload=l=>g(l.target.result);k.onerror=l=>c(l);k.readAsText(e)})}async function v(e,g,c){if(!/firefox/i.test(navigator.userAgent))return await A(e);var k=await B(e);k=(new DOMParser).parseFromString(k,
"image/svg+xml");const l=k.documentElement;if(l.hasAttribute("width")&&l.hasAttribute("height")){const n=l.getAttribute("width"),t=l.getAttribute("height");if(!n.includes("%")&&!t.includes("%"))return await A(e)}l.setAttribute("width",g+"px");l.setAttribute("height",c+"px");k=(new XMLSerializer).serializeToString(k);e=new Blob([k],{type:"image/svg+xml"});return await A(e)}function w(e){do{if(e.parentNode&&e.hasAttribute("contenteditable"))return!0;e=e.parentNode}while(e);return!1}const C=new Set(["input",
"textarea","datalist","select"]),H=new Set(["canvas","body","html"]);function z(e){H.has(e.target.tagName.toLowerCase())&&e.preventDefault()}function L(e){(e.metaKey||e.ctrlKey)&&e.preventDefault()}self.C3_GetSvgImageSize=async function(e){e=await A(e);if(0<e.width&&0<e.height)return[e.width,e.height];{e.style.position="absolute";e.style.left="0px";e.style.top="0px";e.style.visibility="hidden";document.body.appendChild(e);const g=e.getBoundingClientRect();document.body.removeChild(e);return[g.width,
g.height]}};self.C3_RasterSvgImageBlob=async function(e,g,c,k,l){e=await v(e,g,c);const n=document.createElement("canvas");n.width=k;n.height=l;n.getContext("2d").drawImage(e,0,0,g,c);return n};let E=!1;document.addEventListener("pause",()=>E=!0);document.addEventListener("resume",()=>E=!1);function M(){try{return window.parent&&window.parent.document.hasFocus()}catch(e){return!1}}f.Da(class extends self.sa{constructor(e){super(e,"runtime");this.Vd=!0;this.Ra=-1;this.fd="any";this.Md=this.Nd=!1;this.Ka=
this.sb=this.Aa=null;this.bc=this.ac=0;e.C("canvas","update-size",k=>this.Wf(k));e.C("runtime","invoke-download",k=>this.If(k));e.C("runtime","raster-svg-image",k=>this.Pf(k));e.C("runtime","get-svg-image-size",k=>this.Gf(k));e.C("runtime","set-target-orientation",k=>this.Uf(k));e.C("runtime","register-sw",()=>this.Rf());e.C("runtime","post-to-debugger",k=>this.Hd(k));e.C("runtime","go-to-script",k=>this.Hd(k));e.C("runtime","before-start-ticking",()=>this.tf());e.C("runtime","debug-highlight",k=>
this.wf(k));e.C("runtime","enable-device-orientation",()=>this.Ze());e.C("runtime","enable-device-motion",()=>this.Ye());e.C("runtime","add-stylesheet",k=>this.sf(k));e.C("runtime","alert",k=>this.Fc(k));e.C("runtime","hide-cordova-splash",()=>this.Hf());const g=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",k=>{const l=k.target;g.has(l.tagName.toLowerCase())||w(l)||k.preventDefault()});const c=e.G;window.addEventListener("selectstart",z);window.addEventListener("gesturehold",
z);c.addEventListener("selectstart",z);c.addEventListener("gesturehold",z);window.addEventListener("touchstart",z,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",z,{passive:!1}),c.addEventListener("pointerdown",z)):c.addEventListener("touchstart",z);this.pb=0;window.addEventListener("mousedown",k=>{1===k.button&&k.preventDefault()});window.addEventListener("mousewheel",L,{passive:!1});window.addEventListener("wheel",L,{passive:!1});window.addEventListener("resize",
()=>this.Xf());window.addEventListener("fullscreenchange",()=>this.Ya());window.addEventListener("webkitfullscreenchange",()=>this.Ya());window.addEventListener("mozfullscreenchange",()=>this.Ya());window.addEventListener("fullscreenerror",k=>this.Hc(k));window.addEventListener("webkitfullscreenerror",k=>this.Hc(k));window.addEventListener("mozfullscreenerror",k=>this.Hc(k));e.rc()&&window.addEventListener("focusout",()=>{{const n=document.activeElement;if(n){var k=n.tagName.toLowerCase();var l=new Set("email number password search tel text url".split(" "));
k="textarea"===k?!0:"input"===k?l.has(n.type.toLowerCase()||"text"):w(n)}else k=!1}k||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=k=>this.Zf(k);this.Ma=new Set;this.Xb=new WeakSet;this.oa=!1}tf(){"cordova"===this.v.s?(document.addEventListener("pause",()=>this.Lc(!0)),document.addEventListener("resume",()=>this.Lc(!1))):document.addEventListener("visibilitychange",()=>this.Lc(document.hidden));return{isSuspended:!(!document.hidden&&!E)}}ld(){window.addEventListener("focus",()=>
this.$a("window-focus"));window.addEventListener("blur",()=>{this.$a("window-blur",{parentHasFocus:M()});this.pb=0});window.addEventListener("focusin",g=>{g=g.target;(C.has(g.tagName.toLowerCase())||w(g))&&this.$a("keyboard-blur")});window.addEventListener("keydown",g=>this.Gd("keydown",g));window.addEventListener("keyup",g=>this.Gd("keyup",g));window.addEventListener("dblclick",g=>this.Ic("dblclick",g,d));window.addEventListener("wheel",g=>this.Mf(g));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",
g=>{this.Cc(g);this.Za("pointerdown",g)}),this.v.ca&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.sb=new self.Oe(()=>this.hf(),5),this.sb.Qd=!0,window.addEventListener("pointerrawupdate",g=>this.Nf(g))):window.addEventListener("pointermove",g=>this.Za("pointermove",g)),window.addEventListener("pointerup",g=>this.Za("pointerup",g)),window.addEventListener("pointercancel",g=>this.Za("pointercancel",g))):(window.addEventListener("mousedown",g=>{this.Cc(g);this.Jc("pointerdown",
g)}),window.addEventListener("mousemove",g=>this.Jc("pointermove",g)),window.addEventListener("mouseup",g=>this.Jc("pointerup",g)),window.addEventListener("touchstart",g=>{this.Cc(g);this.Ib("pointerdown",g)}),window.addEventListener("touchmove",g=>this.Ib("pointermove",g)),window.addEventListener("touchend",g=>this.Ib("pointerup",g)),window.addEventListener("touchcancel",g=>this.Ib("pointercancel",g)));const e=()=>this.Mc();window.addEventListener("pointerup",e,!0);window.addEventListener("touchend",
e,!0);window.addEventListener("click",e,!0);window.addEventListener("keydown",e,!0);window.addEventListener("gamepadconnected",e,!0)}$a(e,g){u(this,e,g||null,m)}ya(){return this.v.ya()}xa(){return this.v.xa()}Xf(){const e=this.ya(),g=this.xa();this.$a("window-resize",{innerWidth:e,innerHeight:g,devicePixelRatio:window.devicePixelRatio,isFullscreen:f.Wa()});this.v.rc()&&(-1!==this.Ra&&clearTimeout(this.Ra),this.Id(e,g,0))}gg(e,g,c){-1!==this.Ra&&clearTimeout(this.Ra);this.Ra=setTimeout(()=>this.Id(e,
g,c),48)}Id(e,g,c){const k=this.ya(),l=this.xa();this.Ra=-1;k!=e||l!=g?this.$a("window-resize",{innerWidth:k,innerHeight:l,devicePixelRatio:window.devicePixelRatio,isFullscreen:f.Wa()}):10>c&&this.gg(k,l,c+1)}Uf(e){this.fd=e.targetOrientation}zg(){const e=this.fd;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(e).catch(g=>console.warn("[Construct 3] Failed to lock orientation: ",g));else try{let g=!1;screen.lockOrientation?g=screen.lockOrientation(e):screen.webkitLockOrientation?
g=screen.webkitLockOrientation(e):screen.mozLockOrientation?g=screen.mozLockOrientation(e):screen.msLockOrientation&&(g=screen.msLockOrientation(e));g||console.warn("[Construct 3] Failed to lock orientation")}catch(g){console.warn("[Construct 3] Failed to lock orientation: ",g)}}Ya(){const e=f.Wa();e&&"any"!==this.fd&&this.zg();u(this,"fullscreenchange",{isFullscreen:e,innerWidth:this.ya(),innerHeight:this.xa()})}Hc(e){console.warn("[Construct 3] Fullscreen request failed: ",e);u(this,"fullscreenerror",
{isFullscreen:f.Wa(),innerWidth:this.ya(),innerHeight:this.xa()})}Lc(e){e?this.v.yc():this.v.Nc();u(this,"visibilitychange",{hidden:e})}Gd(e,g){"Backspace"===g.key&&z(g);const c=b.get(g.code)||g.code;D(this,e,{code:c,key:g.key,which:g.which,repeat:g.repeat,altKey:g.altKey,ctrlKey:g.ctrlKey,metaKey:g.metaKey,shiftKey:g.shiftKey,timeStamp:g.timeStamp},d)}Mf(e){u(this,"wheel",{clientX:e.clientX,clientY:e.clientY,pageX:e.pageX,pageY:e.pageY,deltaX:e.deltaX,deltaY:e.deltaY,deltaZ:e.deltaZ,deltaMode:e.deltaMode,
timeStamp:e.timeStamp},d)}Ic(e,g,c){a(g)||D(this,e,{button:g.button,buttons:g.buttons,clientX:g.clientX,clientY:g.clientY,pageX:g.pageX,pageY:g.pageY,movementX:g.movementX||0,movementY:g.movementY||0,timeStamp:g.timeStamp},c)}Jc(e,g){if(!a(g)){var c=this.pb;"pointerdown"===e&&0!==c?e="pointermove":"pointerup"===e&&0!==g.buttons&&(e="pointermove");D(this,e,{pointerId:1,pointerType:"mouse",button:g.button,buttons:g.buttons,lastButtons:c,clientX:g.clientX,clientY:g.clientY,pageX:g.pageX,pageY:g.pageY,
movementX:g.movementX||0,movementY:g.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:g.timeStamp},d);this.pb=g.buttons;this.Ic(g.type,g,h)}}Za(e,g){if(this.sb&&"pointermove"!==e){var c=this.sb;c.hb||(K(c),c.Ub=Date.now())}c=0;"mouse"===g.pointerType&&(c=this.pb);D(this,e,{pointerId:g.pointerId,pointerType:g.pointerType,button:g.button,buttons:g.buttons,lastButtons:c,clientX:g.clientX,clientY:g.clientY,pageX:g.pageX,pageY:g.pageY,movementX:(g.movementX||
0)+this.ac,movementY:(g.movementY||0)+this.bc,width:g.width||0,height:g.height||0,pressure:g.pressure||0,tangentialPressure:g.tangentialPressure||0,tiltX:g.tiltX||0,tiltY:g.tiltY||0,twist:g.twist||0,timeStamp:g.timeStamp},d);this.bc=this.ac=0;"mouse"===g.pointerType&&(c="mousemove","pointerdown"===e?c="mousedown":"pointerup"===e&&(c="mouseup"),this.Ic(c,g,h),this.pb=g.buttons)}Nf(e){this.Ka&&(this.ac+=this.Ka.movementX||0,this.bc+=this.Ka.movementY||0);this.Ka=e;e=this.sb;if(-1===e.Sa){var g=Date.now(),
c=g-e.Ub,k=e.Fg;c>=k&&e.Qd?(e.Ub=g,e.hb=!0,e.Rc(),e.hb=!1):e.Sa=self.setTimeout(e.ie,Math.max(k-c,4))}}hf(){this.Za("pointermove",this.Ka);this.Ka=null}Ib(e,g){for(let c=0,k=g.changedTouches.length;c<k;++c){const l=g.changedTouches[c];D(this,e,{pointerId:l.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:l.clientX,clientY:l.clientY,pageX:l.pageX,pageY:l.pageY,movementX:g.movementX||0,movementY:g.movementY||0,width:2*(l.radiusX||l.webkitRadiusX||0),height:2*(l.radiusY||l.webkitRadiusY||
0),pressure:l.force||l.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:l.rotationAngle||0,timeStamp:g.timeStamp},d)}}Cc(e){window!==window.top&&window.focus();this.Ed(e.target)&&document.activeElement&&!this.Ed(document.activeElement)&&document.activeElement.blur()}Ed(e){return!e||e===document||e===window||e===document.body||"canvas"===e.tagName.toLowerCase()}Ze(){this.Nd||(this.Nd=!0,window.addEventListener("deviceorientation",e=>this.yf(e)),window.addEventListener("deviceorientationabsolute",
e=>this.zf(e)))}Ye(){this.Md||(this.Md=!0,window.addEventListener("devicemotion",e=>this.xf(e)))}yf(e){u(this,"deviceorientation",{absolute:!!e.absolute,alpha:e.alpha||0,beta:e.beta||0,gamma:e.gamma||0,timeStamp:e.timeStamp,webkitCompassHeading:e.webkitCompassHeading,webkitCompassAccuracy:e.webkitCompassAccuracy},d)}zf(e){u(this,"deviceorientationabsolute",{absolute:!!e.absolute,alpha:e.alpha||0,beta:e.beta||0,gamma:e.gamma||0,timeStamp:e.timeStamp},d)}xf(e){let g=null;var c=e.acceleration;c&&(g=
{x:c.x||0,y:c.y||0,z:c.z||0});c=null;var k=e.accelerationIncludingGravity;k&&(c={x:k.x||0,y:k.y||0,z:k.z||0});k=null;const l=e.rotationRate;l&&(k={alpha:l.alpha||0,beta:l.beta||0,gamma:l.gamma||0});u(this,"devicemotion",{acceleration:g,accelerationIncludingGravity:c,rotationRate:k,interval:e.interval,timeStamp:e.timeStamp},d)}Wf(e){const g=this.v.G;g.style.width=e.styleWidth+"px";g.style.height=e.styleHeight+"px";g.style.marginLeft=e.marginLeft+"px";g.style.marginTop=e.marginTop+"px";this.Vd&&(g.style.display=
"",this.Vd=!1)}If(e){const g=e.url;e=e.filename;const c=document.createElement("a"),k=document.body;c.textContent=e;c.href=g;c.download=e;k.appendChild(c);c.click();k.removeChild(c)}async Pf(e){var g=e.imageBitmapOpts;e=await self.C3_RasterSvgImageBlob(e.blob,e.imageWidth,e.imageHeight,e.surfaceWidth,e.surfaceHeight);g=g?await createImageBitmap(e,g):await createImageBitmap(e);return{imageBitmap:g,transferables:[g]}}async Gf(e){return await self.C3_GetSvgImageSize(e.blob)}async sf(e){await p(e.url)}Mc(){var e=
[...this.Ma];this.Ma.clear();if(!this.oa)for(const g of e)(e=g.play())&&e.catch(()=>{this.Xb.has(g)||this.Ma.add(g)})}wa(e){if("function"!==typeof e.play)throw Error("missing play function");this.Xb.delete(e);let g;try{g=e.play()}catch(c){this.Ma.add(e);return}g&&g.catch(()=>{this.Xb.has(e)||this.Ma.add(e)})}Fa(e){this.Ma.delete(e);this.Xb.add(e)}Db(e){this.oa=!!e}Hf(){navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()}wf(e){if(e.show){this.Aa||(this.Aa=document.createElement("div"),
this.Aa.id="inspectOutline",document.body.appendChild(this.Aa));var g=this.Aa;g.style.display="";g.style.left=e.left-1+"px";g.style.top=e.top-1+"px";g.style.width=e.width+2+"px";g.style.height=e.height+2+"px";g.textContent=e.name}else this.Aa&&(this.Aa.style.display="none")}Rf(){window.C3_RegisterSW&&window.C3_RegisterSW()}Hd(e){window.c3_postToMessagePort&&(e.from="runtime",window.c3_postToMessagePort(e))}qf(e,g){return this.v.td(this.bb,"js-invoke-function",{name:e,params:g},void 0,void 0)}Fc(e){alert(e.message)}Zf(e){"entered-fullscreen"===
e?(f.Lb(!0),this.Ya()):"exited-fullscreen"===e?(f.Lb(!1),this.Ya()):console.warn("Unknown wrapper message: ",e)}})}"use strict";async function O(f){if(f.Eg)throw Error("already initialised");f.Eg=!0;var a=f.ec.Bc("dispatchworker.js");f.Tc=await f.ec.lc(a,f.F,{name:"DispatchWorker"});a=new MessageChannel;f.Xc=a.port1;f.Tc.postMessage({type:"_init","in-port":a.port2},[a.port2]);f.dd=await Q(f)}function P(f){return[f.Xc,f.dd]}
async function Q(f){const a=f.Xd.length;var b=f.ec.Bc("jobworker.js");b=await f.ec.lc(b,f.F,{name:"JobWorker"+a});const d=new MessageChannel,h=new MessageChannel;f.Tc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);b.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":h.port2},[d.port2,h.port2]);f.Xd.push(b);return h.port1}
self.Ke=class{constructor(f){this.ec=f;this.F=f.F;this.F="preview"===f.s?this.F+"workers/":this.F+f.fc;this.Hg=Math.min(navigator.hardwareConcurrency||2,16);this.Tc=null;this.Xd=[];this.dd=this.Xc=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.fa({Wg:!1,Xg:"workermain.js",Ta:["scripts/c3runtime.js"],jc:[],hd:"",Tg:"scripts/",kd:[],je:"html5"}));"use strict";
{let f=!1;self.fa.Da(class extends self.sa{constructor(a){super(a,"gamepad");this.Wd=!!navigator.getGamepads;this.Zc=!1;G(this,"is-supported",()=>this.Wd);G(this,"ready",()=>this.Qf());G(this,"vibrate",b=>this.Ef(b));G(this,"reset-vibrate",b=>this.Df(b));window.addEventListener("gamepadconnected",b=>this.Bf(b));window.addEventListener("gamepaddisconnected",b=>this.Cf(b));window.addEventListener("unload",()=>this.Yf())}Fb(){try{return Array.from(navigator.getGamepads()).filter(a=>a&&a.connected)}catch(a){return f||
(console.warn("[Construct 3] Failed to access gamepads: ",a),f=!0),[]}}Qf(){this.Zc=!0;for(const a of this.Fb())u(this,"gamepad-connected",{index:a.index,id:a.id});this.Wd&&J(this)}Bf(a){this.Zc&&(a=a.gamepad,u(this,"gamepad-connected",{index:a.index,id:a.id}))}Cf(a){this.Zc&&u(this,"gamepad-disconnected",{index:a.gamepad.index})}va(){var a=this.Fb();a.length&&(a=a.map(b=>({index:b.index,id:b.id,buttons:b.buttons.map(d=>({pressed:d.pressed,value:d.value})),axes:b.axes})),u(this,"input-update",a))}Cd(a){for(const b of this.Fb())if(b.index===
a)return b;return null}async Ef(a){var b=this.Cd(a.index);if(b&&(b=b.vibrationActuator)&&b.playEffect)try{await b.playEffect("dual-rumble",{duration:a.duration,startDelay:0,weakMagnitude:a.weakMag,strongMagnitude:a.strongMag})}catch(d){console.warn("[Gamepad] Failed to vibrate gamepad: ",d)}}Df(a){(a=this.Cd(a.index))&&(a=a.vibrationActuator)&&a.reset&&a.reset()}Yf(){for(const a of this.Fb()){const b=a.vibrationActuator;b&&b.reset&&b.reset()}}})}"use strict";
async function R(f,a){a=a.type;let b=!0;0===a?b=await S():1===a&&(b=await T());u(f,"permission-result",{type:a,result:b})}async function S(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(f){return console.warn("[Touch] Failed to request orientation permission: ",f),!1}}
async function T(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(f){return console.warn("[Touch] Failed to request motion permission: ",f),!1}}self.fa.Da(class extends self.sa{constructor(f){super(f,"touch");G(this,"request-permission",a=>R(this,a))}});"use strict";
function U(f){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>u(f,"sw-message",a.data))}
function V(f){f=f.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(f).catch(a=>console.warn("[Construct 3] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(f):screen.webkitLockOrientation?a=screen.webkitLockOrientation(f):screen.mozLockOrientation?a=screen.mozLockOrientation(f):screen.msLockOrientation&&(a=screen.msLockOrientation(f));a||console.warn("[Construct 3] Failed to lock orientation")}catch(a){console.warn("[Construct 3] Failed to lock orientation: ",
a)}}
self.fa.Da(class extends self.sa{constructor(f){super(f,"browser");this.s="";I(this,[["get-initial-state",a=>{this.s=a.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isScirraArcade:"undefined"!==typeof window.is_scirra_arcade}}],["ready-for-sw-messages",()=>U(this)],
["alert",a=>this.Fc(a)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",a=>this.Kc(a)],["vibrate",a=>{navigator.vibrate&&navigator.vibrate(a.pattern)}],["lock-orientation",a=>V(a)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?screen.webkitUnlockOrientation():
screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}],["navigate",a=>{var b=a.type;if("back"===b)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.history.back();else if("forward"===b)window.history.forward();else if("reload"===b)location.reload();else if("url"===b){b=a.url;const d=a.target;a=a.exportType;self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(b,"_system"):"preview"===
a||"windows-webview2"===a?window.open(b,"_blank"):this.bh||(2===d?window.top.location=b:1===d?window.parent.location=b:window.location=b)}else"new-window"===b&&(b=a.url,a=a.tag,self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(b,"_system"):window.open(b,a))}],["request-fullscreen",a=>{if("windows-webview2"===this.s||"macos-wkwebview"===this.s)self.fa.Lb(!0),this.v.Oc({type:"set-fullscreen",fullscreen:!0});else{const b={navigationUI:"auto"};a=a.navUI;1===a?b.navigationUI="hide":
2===a&&(b.navigationUI="show");a=document.documentElement;a.requestFullscreen?a.requestFullscreen(b):a.mozRequestFullScreen?a.mozRequestFullScreen(b):a.msRequestFullscreen?a.msRequestFullscreen(b):a.webkitRequestFullScreen&&("undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):a.webkitRequestFullScreen())}}],["exit-fullscreen",()=>{"windows-webview2"===this.s||"macos-wkwebview"===this.s?(self.fa.Lb(!1),this.v.Oc({type:"set-fullscreen",fullscreen:!1})):
document.exitFullscreen?document.exitFullscreen():document.mozCancelFullScreen?document.mozCancelFullScreen():document.msExitFullscreen?document.msExitFullscreen():document.webkitCancelFullScreen&&document.webkitCancelFullScreen()}],["set-hash",a=>{location.hash=a.hash}]]);window.addEventListener("online",()=>{u(this,"online-state",{isOnline:!0})});window.addEventListener("offline",()=>{u(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{u(this,"hashchange",{location:location.toString()})});
document.addEventListener("backbutton",()=>{u(this,"backbutton")})}Fc(f){alert(f.message)}Kc(f){f=f.isFocus;if("nwjs"===this.s){const a="nwjs"===this.s?nw.Window.get():null;f?a.focus():a.blur()}else f?window.focus():window.blur()}});"use strict";
{const f=180/Math.PI;self.da=class extends self.sa{constructor(a){super(a,"audio");this.Qb=this.f=null;this.Sb=this.Wc=!1;this.ra=()=>this.Ag();this.$=[];this.D=[];this.ha=null;this.Yd="";this.Zd=-1;this.rb=new Map;this.ad=1;this.oa=!1;this.gd=0;this.hc=1;this.Uc=0;this.ae="HRTF";this.Rd="inverse";this.be=600;this.$d=1E4;this.de=1;this.Td=this.ed=!1;this.ge=this.v.Ie();this.aa=new Map;this.Ia=new Set;this.Yc=!1;this.bd="";this.Ba=null;self.C3Audio_OnMicrophoneStream=(b,d)=>this.Lf(b,d);this.Pb=null;
self.C3Audio_GetOutputStream=()=>this.Ff();self.C3Audio_DOMInterface=this;I(this,[["create-audio-context",b=>this.df(b)],["play",b=>this.ag(b)],["stop",b=>this.xg(b)],["stop-all",()=>this.yg()],["set-paused",b=>this.qg(b)],["set-volume",b=>this.vg(b)],["fade-volume",b=>this.jf(b)],["set-master-volume",b=>this.og(b)],["set-muted",b=>this.pg(b)],["set-silent",b=>this.sg(b)],["set-looping",b=>this.ng(b)],["set-playback-rate",b=>this.rg(b)],["seek",b=>this.hg(b)],["preload",b=>this.bg(b)],["unload",b=>
this.Bg(b)],["unload-all",()=>this.Cg()],["set-suspended",b=>this.tg(b)],["add-effect",b=>this.yd(b)],["set-effect-param",b=>this.kg(b)],["remove-effects",b=>this.dg(b)],["tick",b=>this.Vf(b)],["load-state",b=>this.Jf(b)]])}async df(a){a.isiOSCordova&&(this.ed=!0);this.gd=a.timeScaleMode;this.ae=["equalpower","HRTF","soundfield"][a.panningModel];this.Rd=["linear","inverse","exponential"][a.distanceModel];this.be=a.refDistance;this.$d=a.maxDistance;this.de=a.rolloffFactor;var b={latencyHint:a.latencyHint};
this.ge||(b.sampleRate=48E3);if("undefined"!==typeof AudioContext)this.f=new AudioContext(b);else if("undefined"!==typeof webkitAudioContext)this.f=new webkitAudioContext(b);else throw Error("Web Audio API not supported");this.zd();this.f.onstatechange=()=>{"running"!==this.f.state&&this.zd()};this.Qb=this.f.createGain();this.Qb.connect(this.f.destination);b=a.listenerPos;this.f.listener.setPosition(b[0],b[1],b[2]);this.f.listener.setOrientation(0,0,1,0,-1,0);self.C3_GetAudioContextCurrentTime=()=>
this.mc();try{await Promise.all(a.preloadList.map(d=>this.Gb(d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct 3] Preloading sounds failed: ",d)}return{sampleRate:this.f.sampleRate}}zd(){this.Sb||(this.Wc=!1,window.addEventListener("pointerup",this.ra,!0),window.addEventListener("touchend",this.ra,!0),window.addEventListener("click",this.ra,!0),window.addEventListener("keydown",this.ra,!0),this.Sb=!0)}ff(){this.Sb&&(this.Wc=!0,window.removeEventListener("pointerup",this.ra,!0),window.removeEventListener("touchend",
this.ra,!0),window.removeEventListener("click",this.ra,!0),window.removeEventListener("keydown",this.ra,!0),this.Sb=!1)}Ag(){if(!this.Wc){var a=this.f;"suspended"===a.state&&a.resume&&a.resume();var b=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=b;d.connect(a.destination);d.start(0);"running"===a.state&&this.ff()}}W(){return this.f}mc(){return this.f.currentTime}ta(){return this.Qb}qd(a){return(a=this.aa.get(a.toLowerCase()))?a[0].P():this.ta()}ke(a,b){a=a.toLowerCase();let d=this.aa.get(a);
d||(d=[],this.aa.set(a,d));b.mg(d.length);b.ug(a);d.push(b);this.Kd(a)}Kd(a){let b=this.ta();const d=this.aa.get(a);if(d&&d.length){b=d[0].P();for(let h=0,m=d.length;h<m;++h){const p=d[h];h+1===m?p.S(this.ta()):p.S(d[h+1].P())}}for(const h of this.ma(a))h.Pe(b);this.Ba&&this.bd===a&&(this.Ba.disconnect(),this.Ba.connect(b))}zb(){return this.ad}Ab(){return this.oa}lg(){this.Td=!0}Ce(a,b){return b?this.v.Dg(a).then(d=>{const h=this.f.createBuffer(1,d.length,48E3);h.getChannelData(0).set(d);return h}):
new Promise((d,h)=>{this.f.decodeAudioData(a,d,h)})}wa(a){this.v.wa(a)}Fa(a){this.v.Fa(a)}ud(a){let b=0;for(let d=0,h=this.D.length;d<h;++d){const m=this.D[d];this.D[b]=m;m.L===a?m.c():++b}this.D.length=b}Qe(){let a=0;for(let b=0,d=this.$.length;b<d;++b){const h=this.$[b];this.$[a]=h;h.ua()?h.c():++a}this.$.length=a}*ma(a){if(a)for(const b of this.D)self.da.De(b.Y,a)&&(yield b);else this.ha&&!this.ha.T()&&(yield this.ha)}async Gb(a,b,d,h,m){for(const p of this.$)if(p.Va()===b)return await W(p),p;
if(m)return null;h&&(this.ed||this.Td)&&this.Qe();m="audio/webm; codecs=opus"===d&&!this.ge;h&&m&&this.lg();a=!h||this.ed||m?new self.ye(this,a,b,d,h,m):new self.we(this,a,b,d,h);this.$.push(a);await W(a);return a}async Ac(a,b,d,h,m){for(const p of this.D)if(p.Va()===b&&(p.kc()||m))return p.Se(h),p;a=await this.Gb(a,b,d,m);h="html5"===a.Pc?new self.xe(a.i,a,h):new self.ze(a.i,a,h);this.D.push(h);return h}We(a){let b=this.rb.get(a);if(!b){let d=null;b={jd:0,Sg:new Promise(h=>d=h),resolve:d};this.rb.set(a,
b)}b.jd++}eg(a){const b=this.rb.get(a);if(!b)throw Error("expected pending tag");b.jd--;0===b.jd&&(b.resolve(),this.rb.delete(a))}xc(a){a||(a=this.Yd);return(a=this.rb.get(a))?a.Sg:Promise.resolve()}Hb(){if(0<this.Ia.size)J(this);else for(const a of this.D)if(a.rd()){J(this);break}}va(){for(var a of this.Ia)a.va();a=this.mc();for(var b of this.D)b.va(a);b=this.D.filter(d=>d.rd()).map(d=>d.Ua());u(this,"state",{tickCount:this.Zd,audioInstances:b,analysers:[...this.Ia].map(d=>d.Fe())});0===b.length&&
0===this.Ia.size&&this.Tb&&(this.v.fg(this.he),this.Tb=!1)}tc(a,b,d){u(this,"trigger",{type:a,tag:b,aiid:d})}async ag(a){const b=a.originalUrl,d=a.url,h=a.type,m=a.isMusic,p=a.tag,x=a.isLooping,A=a.vol,B=a.pos,v=a.panning;let w=a.off;0<w&&!a.trueClock&&(this.f.getOutputTimestamp?(a=this.f.getOutputTimestamp(),w=w-a.performanceTime/1E3+a.contextTime):w=w-performance.now()/1E3+this.f.currentTime);this.Yd=p;this.We(p);try{this.ha=await this.Ac(b,d,h,p,m),v?(this.ha.Cb(!0),this.ha.Re(v.x,v.y,v.angle,
v.innerAngle,v.outerAngle,v.outerGain),v.hasOwnProperty("uid")&&this.ha.Te(v.uid)):this.ha.Cb(!1),this.ha.Play(x,A,B,w)}catch(C){console.error("[Construct 3] Audio: error starting playback: ",C);return}finally{this.eg(p)}J(this)}xg(a){a=a.tag;for(const b of this.ma(a))b.na()}yg(){for(const a of this.D)a.na()}qg(a){const b=a.tag;a=a.paused;for(const d of this.ma(b))a?d.Xa():d.Bb();this.Hb()}vg(a){const b=a.tag;a=a.vol;for(const d of this.ma(b))d.Eb(a)}async jf(a){const b=a.tag,d=a.vol,h=a.duration;
a=a.stopOnEnd;await this.xc(b);for(const m of this.ma(b))m.Ee(d,h,a);this.Hb()}og(a){this.ad=a.vol;for(const b of this.D)b.Nb()}pg(a){const b=a.tag;a=a.isMuted;for(const d of this.ma(b))d.vd(a)}sg(a){this.oa=a.isSilent;this.v.Db(this.oa);for(const b of this.D)b.Mb()}ng(a){const b=a.tag;a=a.isLooping;for(const d of this.ma(b))d.vc(a)}async rg(a){const b=a.tag;a=a.rate;await this.xc(b);for(const d of this.ma(b))d.xd(a)}async hg(a){const b=a.tag;a=a.pos;await this.xc(b);for(const d of this.ma(b))d.uc(a)}async bg(a){const b=
a.originalUrl,d=a.url,h=a.type;a=a.isMusic;try{await this.Ac(b,d,h,"",a)}catch(m){console.error("[Construct 3] Audio: error preloading: ",m)}}async Bg(a){if(a=await this.Gb("",a.url,a.type,a.isMusic,!0))a.c(),a=this.$.indexOf(a),-1!==a&&this.$.splice(a,1)}Cg(){for(const a of this.$)a.c();this.$.length=0}tg(a){a=a.isSuspended;!a&&this.f.resume&&this.f.resume();for(const b of this.D)b.wc(a);a&&this.f.suspend&&this.f.suspend()}Vf(a){this.hc=a.timeScale;this.Uc=a.gameTime;this.Zd=a.tickCount;if(0!==this.gd)for(var b of this.D)b.Ha();
(b=a.listenerPos)&&this.f.listener.setPosition(b[0],b[1],b[2]);for(const d of a.instPans){a=d.uid;for(const h of this.D)h.ga===a&&h.wd(d.x,d.y,d.angle)}}async yd(a){var b=a.type;const d=a.tag;var h=a.params;if("filter"===b)h=new self.qe(this,...h);else if("delay"===b)h=new self.oe(this,...h);else if("convolution"===b){b=null;try{b=await this.Gb(a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(m){console.log("[Construct 3] Audio: error loading convolution: ",m);return}h=new self.ne(this,b.Z,
...h);h.ig(a.bufferOriginalUrl,a.bufferType)}else if("flanger"===b)h=new self.re(this,...h);else if("phaser"===b)h=new self.te(this,...h);else if("gain"===b)h=new self.se(this,...h);else if("tremolo"===b)h=new self.ve(this,...h);else if("ringmod"===b)h=new self.ue(this,...h);else if("distortion"===b)h=new self.pe(this,...h);else if("compressor"===b)h=new self.me(this,...h);else if("analyser"===b)h=new self.le(this,...h);else throw Error("invalid effect type");this.ke(d,h);this.Jd()}kg(a){const b=
a.index,d=a.param,h=a.value,m=a.ramp,p=a.time;a=this.aa.get(a.tag);!a||0>b||b>=a.length||(a[b].X(d,h,m,p),this.Jd())}dg(a){a=a.tag.toLowerCase();const b=this.aa.get(a);if(b&&b.length){for(const d of b)d.c();this.aa.delete(a);this.Kd(a)}}Ve(a){this.Ia.add(a);this.Hb()}cg(a){this.Ia.delete(a)}Jd(){this.Yc||(this.Yc=!0,Promise.resolve().then(()=>this.gf()))}gf(){const a={};for(const [b,d]of this.aa)a[b]=d.map(h=>h.Ua());u(this,"fxstate",{fxstate:a});this.Yc=!1}async Jf(a){const b=a.saveLoadMode;if(3!==
b)for(var d of this.D)d.ua()&&1===b||(d.ua()||2!==b)&&d.na();for(const h of this.aa.values())for(const m of h)m.c();this.aa.clear();this.hc=a.timeScale;this.Uc=a.gameTime;d=a.listenerPos;this.f.listener.setPosition(d[0],d[1],d[2]);this.oa=a.isSilent;this.v.Db(this.oa);this.ad=a.masterVolume;d=[];for(const h of Object.values(a.effects))d.push(Promise.all(h.map(m=>this.yd(m))));await Promise.all(d);await Promise.all(a.playing.map(h=>this.rf(h,b)));this.Hb()}async rf(a,b){if(3!==b){var d=a.bufferOriginalUrl,
h=a.bufferUrl,m=a.bufferType,p=a.isMusic,x=a.tag,A=a.isLooping,B=a.volume,v=a.playbackTime;if(!p||1!==b)if(p||2!==b){b=null;try{b=await this.Ac(d,h,m,x,p)}catch(w){console.error("[Construct 3] Audio: error loading audio state: ",w);return}b.Ne(a.pan);b.Play(A,B,v,0);a.isPlaying||b.Xa();b.Ec(a)}}}Lf(a,b){this.Ba&&this.Ba.disconnect();this.bd=b.toLowerCase();this.Ba=this.f.createMediaStreamSource(a);this.Ba.connect(this.qd(this.bd))}Ff(){this.Pb||(this.Pb=this.f.createMediaStreamDestination(),this.Qb.connect(this.Pb));
return this.Pb.stream}static De(a,b){return a.length!==b.length?!1:a===b?!0:a.toLowerCase()===b.toLowerCase()}static Ue(a){return a*f}static Be(a){return Math.pow(10,a/20)}static pd(a){return Math.max(Math.min(self.da.Be(a),1),0)}static Me(a){return Math.log(a)/Math.log(10)*20}static Le(a){return self.da.Me(Math.max(Math.min(a,1),0))}static Ng(a,b){return 1-Math.exp(-b*a)}};self.fa.Da(self.da)}"use strict";function W(f){f.Vb||(f.Vb=f.Dc());return f.Vb}
self.md=class{constructor(f,a,b,d,h){this.i=f;this.Jg=a;this.Ca=b;this.R=d;this.Gg=h;this.Pc="";this.Vb=null}c(){this.Vb=this.i=null}Dc(){}W(){return this.i.W()}oc(){return this.Jg}Va(){return this.Ca}nc(){return this.R}ua(){return this.Gg}ea(){}};"use strict";
self.we=class extends self.md{constructor(f,a,b,d,h){super(f,a,b,d,h);this.Pc="html5";this.K=new Audio;this.K.crossOrigin="anonymous";this.K.autoplay=!1;this.K.preload="auto";this.lb=this.mb=null;this.K.addEventListener("canplaythrough",()=>!0);this.qb=this.W().createGain();this.ob=null;this.K.addEventListener("canplay",()=>{this.mb&&(this.mb(),this.lb=this.mb=null);!this.ob&&this.K&&(this.ob=this.W().createMediaElementSource(this.K),this.ob.connect(this.qb))});this.onended=null;this.K.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.K.addEventListener("error",m=>{console.error(`[Construct 3] Audio '${this.Ca}' error: `,m);this.lb&&(this.lb(m),this.lb=this.mb=null)})}c(){this.i.ud(this);this.qb.disconnect();this.qb=null;this.ob.disconnect();this.ob=null;this.K&&!this.K.paused&&this.K.pause();this.K=this.onended=null;super.c()}Dc(){return new Promise((f,a)=>{this.mb=f;this.lb=a;this.K.src=this.Ca})}O(){return this.K}ea(){return this.K.duration}};"use strict";
async function X(f){if(f.za)return f.za;var a=f.i.v;if("cordova"===a.s&&a.sd(f.Ca)&&a.ib)f.za=await a.xb(f.Ca);else{a=await fetch(f.Ca);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);f.za=await a.arrayBuffer()}}async function Y(f){if(f.Z)return f.Z;f.Z=await f.i.Ce(f.za,f.Ig);f.za=null}
self.ye=class extends self.md{constructor(f,a,b,d,h,m){super(f,a,b,d,h);this.Pc="webaudio";this.Z=this.za=null;this.Ig=!!m}c(){this.i.ud(this);this.Z=this.za=null;super.c()}async Dc(){try{await X(this),await Y(this)}catch(f){console.error(`[Construct 3] Failed to load audio '${this.Ca}': `,f)}}ea(){return this.Z?this.Z.duration:0}};"use strict";
{let f=0;self.nd=class{constructor(a,b,d){this.i=a;this.L=b;this.Y=d;this.Ob=f++;this.M=this.W().createGain();this.M.connect(this.ta());this.B=null;this.jb=!1;this.ka=[0,0,0];this.ja=[0,0,0];this.I=!0;this.V=this.la=this.H=!1;this.ub=1;this.Ja=!1;this.qa=1;a=this.i.gd;this.$c=1===a&&!this.ua()||2===a;this.fb=this.ga=-1;this.fe=!1}c(){this.L=this.i=null;this.B&&(this.B.disconnect(),this.B=null);this.M.disconnect();this.M=null}W(){return this.i.W()}ta(){return this.i.qd(this.Y)}zb(){return this.i.zb()}yb(){return this.$c?
this.i.Uc:performance.now()/1E3}oc(){return this.L.oc()}Va(){return this.L.Va()}nc(){return this.L.nc()}ua(){return this.L.ua()}Se(a){this.Y=a}T(){}kc(){}IsPlaying(){return!this.I&&!this.H&&!this.T()}rd(){return!this.I&&!this.T()}Ea(){}ea(){return this.L.ea()}Play(){}na(){}Xa(){}Bb(){}Eb(a){this.ub=a;this.M.gain.cancelScheduledValues(0);this.fb=-1;this.M.gain.value=this.pc()}Ee(a,b,d){if(!this.Ja){a*=this.zb();var h=this.M.gain;h.cancelScheduledValues(0);var m=this.i.mc();b=m+b;h.setValueAtTime(h.value,
m);h.linearRampToValueAtTime(a,b);this.ub=a;this.fb=b;this.fe=d}}Nb(){this.Eb(this.ub)}va(a){-1!==this.fb&&a>=this.fb&&(this.fb=-1,this.fe&&this.na(),this.i.tc("fade-ended",this.Y,this.Ob))}pc(){const a=this.ub*this.zb();return isFinite(a)?a:0}vd(a){a=!!a;this.Ja!==a&&(this.Ja=a,this.Mb())}Ab(){return this.i.Ab()}Mb(){}vc(){}xd(a){this.qa!==a&&(this.qa=a,this.Ha())}Ha(){}uc(){}wc(){}Cb(a){a=!!a;this.jb!==a&&((this.jb=a)?(this.B||(this.B=this.W().createPanner(),this.B.panningModel=this.i.ae,this.B.distanceModel=
this.i.Rd,this.B.refDistance=this.i.be,this.B.maxDistance=this.i.$d,this.B.rolloffFactor=this.i.de),this.M.disconnect(),this.M.connect(this.B),this.B.connect(this.ta())):(this.B.disconnect(),this.M.disconnect(),this.M.connect(this.ta())))}Re(a,b,d,h,m,p){this.jb&&(this.wd(a,b,d),a=self.da.Ue,this.B.coneInnerAngle=a(h),this.B.coneOuterAngle=a(m),this.B.coneOuterGain=p)}wd(a,b,d){this.jb&&(this.ka[0]=a,this.ka[1]=b,this.ka[2]=0,this.ja[0]=Math.cos(d),this.ja[1]=Math.sin(d),this.ja[2]=0,this.B.setPosition(...this.ka),
this.B.setOrientation(...this.ja))}Te(a){this.ga=a}qc(){}Pe(a){const b=this.B||this.M;b.disconnect();b.connect(a)}Ua(){return{aiid:this.Ob,tag:this.Y,duration:this.ea(),volume:this.ub,isPlaying:this.IsPlaying(),playbackTime:this.Ea(),playbackRate:this.qa,uid:this.ga,bufferOriginalUrl:this.oc(),bufferUrl:"",bufferType:this.nc(),isMusic:this.ua(),isLooping:this.V,isMuted:this.Ja,resumePosition:this.qc(),pan:this.Ge()}}Ec(a){this.xd(a.playbackRate);this.vd(a.isMuted)}Ge(){if(!this.B)return null;const a=
this.B;return{pos:this.ka,orient:this.ja,cia:a.coneInnerAngle,coa:a.coneOuterAngle,cog:a.coneOuterGain,uid:this.ga}}Ne(a){if(a){this.Cb(!0);a=this.B;var b=a.pos;this.ka[0]=b[0];this.ka[1]=b[1];this.ka[2]=b[2];b=a.orient;this.ja[0]=b[0];this.ja[1]=b[1];this.ja[2]=b[2];a.setPosition(...this.ka);a.setOrientation(...this.ja);a.coneInnerAngle=a.cia;a.coneOuterAngle=a.coa;a.coneOuterGain=a.cog;this.ga=a.uid}else this.Cb(!1)}}}"use strict";
self.xe=class extends self.nd{constructor(f,a,b){super(f,a,b);this.L.qb.connect(this.M);this.L.onended=()=>this.Gc()}c(){this.na();this.L.qb.disconnect();super.c()}O(){return this.L.O()}Gc(){this.I=!0;this.ga=-1;this.i.tc("ended",this.Y,this.Ob)}T(){return this.O().ended}kc(){return this.I?!0:this.T()}Ea(){let f=this.O().currentTime;this.V||(f=Math.min(f,this.ea()));return f}Play(f,a,b){const d=this.O();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==f&&(d.loop=f);this.Eb(a);d.muted&&(d.muted=!1);
if(d.currentTime!==b)try{d.currentTime=b}catch(h){console.warn(`[Construct 3] Exception seeking audio '${this.L.Va()}' to position '${b}': `,h)}this.i.wa(d);this.H=this.I=!1;this.V=f;this.qa=1}na(){const f=this.O();f.paused||f.pause();this.i.Fa(f);this.I=!0;this.H=!1;this.ga=-1}Xa(){if(!(this.H||this.I||this.T())){var f=this.O();f.paused||f.pause();this.i.Fa(f);this.H=!0}}Bb(){!this.H||this.I||this.T()||(this.i.wa(this.O()),this.H=!1)}Mb(){this.O().muted=this.Ja||this.Ab()}vc(f){f=!!f;this.V!==f&&
(this.V=f,this.O().loop=f)}Ha(){let f=this.qa;this.$c&&(f*=this.i.hc);try{this.O().playbackRate=f}catch(a){console.warn(`[Construct 3] Unable to set playback rate '${f}':`,a)}}uc(f){if(!this.I&&!this.T())try{this.O().currentTime=f}catch(a){console.warn(`[Construct 3] Error seeking audio to '${f}': `,a)}}qc(){return this.Ea()}wc(f){f?this.IsPlaying()?(this.O().pause(),this.la=!0):this.la=!1:this.la&&(this.i.wa(this.O()),this.la=!1)}};"use strict";
function Z(f){f.j&&f.j.disconnect();f.j=null;f.ab=null}
self.ze=class extends self.nd{constructor(f,a,b){super(f,a,b);this.j=null;this.Yb=d=>this.Gc(d);this.Vc=!0;this.ab=null;this.N=this.Zb=this.$b=0;this.cd=1}c(){this.na();Z(this);this.Yb=null;super.c()}Gc(f){this.H||this.la||f.target!==this.ab||(this.I=this.Vc=!0,this.ga=-1,Z(this),this.i.tc("ended",this.Y,this.Ob))}T(){return!this.I&&this.j&&this.j.loop||this.H?!1:this.Vc}kc(){return!this.j||this.I?!0:this.T()}Ea(){let f;f=this.H?this.N:this.Zb+(this.yb()-this.$b)*this.qa;this.V||(f=Math.min(f,this.ea()));
return f}Play(f,a,b,d){this.cd=1;this.Eb(a);Z(this);this.j=this.W().createBufferSource();this.j.buffer=this.L.Z;this.j.connect(this.M);this.ab=this.j;this.j.onended=this.Yb;this.j.loop=f;this.j.start(d,b);this.H=this.I=this.Vc=!1;this.V=f;this.qa=1;this.$b=this.yb();this.Zb=b}na(){if(this.j)try{this.j.stop(0)}catch(f){}this.I=!0;this.H=!1;this.ga=-1}Xa(){this.H||this.I||this.T()||(this.N=this.Ea(),this.V&&(this.N%=this.ea()),this.H=!0,this.j.stop(0))}Bb(){!this.H||this.I||this.T()||(Z(this),this.j=
this.W().createBufferSource(),this.j.buffer=this.L.Z,this.j.connect(this.M),this.ab=this.j,this.j.onended=this.Yb,this.j.loop=this.V,this.Nb(),this.Ha(),this.j.start(0,this.N),this.$b=this.yb(),this.Zb=this.N,this.H=!1)}pc(){return super.pc()*this.cd}Mb(){this.cd=this.Ja||this.Ab()?0:1;this.Nb()}vc(f){f=!!f;this.V!==f&&(this.V=f,this.j&&(this.j.loop=f))}Ha(){let f=this.qa;this.$c&&(f*=this.i.hc);this.j&&(this.j.playbackRate.value=f)}uc(f){this.I||this.T()||(this.H?this.N=f:(this.Xa(),this.N=f,this.Bb()))}qc(){return this.N}wc(f){f?
this.IsPlaying()?(this.la=!0,this.N=this.Ea(),this.V&&(this.N%=this.ea()),this.j.stop(0)):this.la=!1:this.la&&(Z(this),this.j=this.W().createBufferSource(),this.j.buffer=this.L.Z,this.j.connect(this.M),this.ab=this.j,this.j.onended=this.Yb,this.j.loop=this.V,this.Nb(),this.Ha(),this.j.start(0,this.N),this.$b=this.yb(),this.Zb=this.N,this.la=!1)}Ec(f){super.Ec(f);this.N=f.resumePosition}};"use strict";
{class f{constructor(a){this.i=a;this.f=a.W();this.Ud=-1;this.R=this.Y="";this.g=null}c(){this.f=null}mg(a){this.Ud=a}ug(a){this.Y=a}o(){return this.f.createGain()}P(){}S(){}m(a,b,d,h){a.cancelScheduledValues(0);if(0===h)a.value=b;else{var m=this.f.currentTime;h+=m;switch(d){case 0:a.setValueAtTime(b,h);break;case 1:a.setValueAtTime(a.value,m);a.linearRampToValueAtTime(b,h);break;case 2:a.setValueAtTime(a.value,m),a.exponentialRampToValueAtTime(b,h)}}}Ua(){return{type:this.R,tag:this.Y,params:this.g}}}
self.qe=class extends f{constructor(a,b,d,h,m,p,x){super(a);this.R="filter";this.g=[b,d,h,m,p,x];this.l=this.o();this.b=this.o();this.b.gain.value=x;this.a=this.o();this.a.gain.value=1-x;this.A=this.f.createBiquadFilter();this.A.type=b;this.A.frequency.value=d;this.A.detune.value=h;this.A.Q.value=m;this.A.gain.vlaue=p;this.l.connect(this.A);this.l.connect(this.a);this.A.connect(this.b)}c(){this.l.disconnect();this.A.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();
this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,h){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b,d,h);this.m(this.a.gain,1-b,d,h);break;case 1:this.g[1]=b;this.m(this.A.frequency,b,d,h);break;case 2:this.g[2]=b;this.m(this.A.detune,b,d,h);break;case 3:this.g[3]=b;this.m(this.A.Q,b,d,h);break;case 4:this.g[4]=b,this.m(this.A.gain,b,d,h)}}};self.oe=class extends f{constructor(a,b,d,h){super(a);this.R="delay";this.g=[b,d,h];this.l=
this.o();this.b=this.o();this.b.gain.value=h;this.a=this.o();this.a.gain.value=1-h;this.nb=this.o();this.U=this.f.createDelay(b);this.U.delayTime.value=b;this.eb=this.o();this.eb.gain.value=d;this.l.connect(this.nb);this.l.connect(this.a);this.nb.connect(this.b);this.nb.connect(this.U);this.U.connect(this.eb);this.eb.connect(this.nb)}c(){this.l.disconnect();this.b.disconnect();this.a.disconnect();this.nb.disconnect();this.U.disconnect();this.eb.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);
this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,h){const m=self.da.pd;switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[2]=b;this.m(this.b.gain,b,d,h);this.m(this.a.gain,1-b,d,h);break;case 4:this.g[1]=m(b);this.m(this.eb.gain,m(b),d,h);break;case 5:this.g[0]=b,this.m(this.U.delayTime,b,d,h)}}};self.ne=class extends f{constructor(a,b,d,h){super(a);this.R="convolution";this.g=[d,h];this.Pd=this.Od="";this.l=this.o();this.b=this.o();this.b.gain.value=h;this.a=this.o();this.a.gain.value=
1-h;this.cb=this.f.createConvolver();this.cb.normalize=d;this.cb.buffer=b;this.l.connect(this.cb);this.l.connect(this.a);this.cb.connect(this.b)}c(){this.l.disconnect();this.cb.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,h){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[1]=b,this.m(this.b.gain,b,d,h),this.m(this.a.gain,1-b,d,h)}}ig(a,b){this.Od=a;this.Pd=b}Ua(){const a=
super.Ua();a.bufferOriginalUrl=this.Od;a.bufferUrl="";a.bufferType=this.Pd;return a}};self.re=class extends f{constructor(a,b,d,h,m,p){super(a);this.R="flanger";this.g=[b,d,h,m,p];this.l=this.o();this.a=this.o();this.a.gain.value=1-p/2;this.b=this.o();this.b.gain.value=p/2;this.gb=this.o();this.gb.gain.value=m;this.U=this.f.createDelay(b+d);this.U.delayTime.value=b;this.u=this.f.createOscillator();this.u.frequency.value=h;this.J=this.o();this.J.gain.value=d;this.l.connect(this.U);this.l.connect(this.a);
this.U.connect(this.b);this.U.connect(this.gb);this.gb.connect(this.U);this.u.connect(this.J);this.J.connect(this.U.delayTime);this.u.start(0)}c(){this.u.stop(0);this.l.disconnect();this.U.disconnect();this.u.disconnect();this.J.disconnect();this.a.disconnect();this.b.disconnect();this.gb.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,h){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[4]=b;this.m(this.b.gain,
b/2,d,h);this.m(this.a.gain,1-b/2,d,h);break;case 6:this.g[1]=b/1E3;this.m(this.J.gain,b/1E3,d,h);break;case 7:this.g[2]=b;this.m(this.u.frequency,b,d,h);break;case 8:this.g[3]=b/100,this.m(this.gb.gain,b/100,d,h)}}};self.te=class extends f{constructor(a,b,d,h,m,p,x){super(a);this.R="phaser";this.g=[b,d,h,m,p,x];this.l=this.o();this.a=this.o();this.a.gain.value=1-x/2;this.b=this.o();this.b.gain.value=x/2;this.A=this.f.createBiquadFilter();this.A.type="allpass";this.A.frequency.value=b;this.A.detune.value=
d;this.A.Q.value=h;this.u=this.f.createOscillator();this.u.frequency.value=p;this.J=this.o();this.J.gain.value=m;this.l.connect(this.A);this.l.connect(this.a);this.A.connect(this.b);this.u.connect(this.J);this.J.connect(this.A.frequency);this.u.start(0)}c(){this.u.stop(0);this.l.disconnect();this.A.disconnect();this.u.disconnect();this.J.disconnect();this.a.disconnect();this.b.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,
b,d,h){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b/2,d,h);this.m(this.a.gain,1-b/2,d,h);break;case 1:this.g[0]=b;this.m(this.A.frequency,b,d,h);break;case 2:this.g[1]=b;this.m(this.A.detune,b,d,h);break;case 3:this.g[2]=b;this.m(this.A.Q,b,d,h);break;case 6:this.g[3]=b;this.m(this.J.gain,b,d,h);break;case 7:this.g[4]=b,this.m(this.u.frequency,b,d,h)}}};self.se=class extends f{constructor(a,b){super(a);this.R="gain";this.g=[b];this.h=this.o();this.h.gain.value=
b}c(){this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(a,b,d,h){const m=self.da.pd;switch(a){case 4:this.g[0]=m(b),this.m(this.h.gain,m(b),d,h)}}};self.ve=class extends f{constructor(a,b,d){super(a);this.R="tremolo";this.g=[b,d];this.h=this.o();this.h.gain.value=1-d/2;this.u=this.f.createOscillator();this.u.frequency.value=b;this.J=this.o();this.J.gain.value=d/2;this.u.connect(this.J);this.J.connect(this.h.gain);this.u.start(0)}c(){this.u.stop(0);this.u.disconnect();
this.J.disconnect();this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(a,b,d,h){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.h.gain,1-b/2,d,h);this.m(this.J.gain,b/2,d,h);break;case 7:this.g[0]=b,this.m(this.u.frequency,b,d,h)}}};self.ue=class extends f{constructor(a,b,d){super(a);this.R="ringmod";this.g=[b,d];this.l=this.o();this.b=this.o();this.b.gain.value=d;this.a=this.o();this.a.gain.value=1-d;this.tb=this.o();this.tb.gain.value=
0;this.u=this.f.createOscillator();this.u.frequency.value=b;this.u.connect(this.tb.gain);this.u.start(0);this.l.connect(this.tb);this.l.connect(this.a);this.tb.connect(this.b)}c(){this.u.stop(0);this.u.disconnect();this.tb.disconnect();this.l.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,h){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.b.gain,b,d,h);
this.m(this.a.gain,1-b,d,h);break;case 7:this.g[0]=b,this.m(this.u.frequency,b,d,h)}}};self.pe=class extends f{constructor(a,b,d,h,m,p){super(a);this.R="distortion";this.g=[b,d,h,m,p];this.l=this.o();this.dc=this.o();this.cc=this.o();this.jg(h,m);this.b=this.o();this.b.gain.value=p;this.a=this.o();this.a.gain.value=1-p;this.ic=this.f.createWaveShaper();this.Sc=new Float32Array(65536);this.lf(b,d);this.ic.curve=this.Sc;this.l.connect(this.dc);this.l.connect(this.a);this.dc.connect(this.ic);this.ic.connect(this.cc);
this.cc.connect(this.b)}c(){this.l.disconnect();this.dc.disconnect();this.ic.disconnect();this.cc.disconnect();this.b.disconnect();this.a.disconnect();super.c()}jg(a,b){.01>a&&(a=.01);this.dc.gain.value=a;this.cc.gain.value=Math.pow(1/a,.6)*b}lf(a,b){for(let d=0;32768>d;++d){let h=d/32768;h=this.wg(h,a,b);this.Sc[32768+d]=h;this.Sc[32768-d-1]=-h}}wg(a,b,d){d=1.05*d*b-b;const h=0>a?-a:a;return(h<b?h:b+d*self.da.Ng(h-b,1/d))*(0>a?-1:1)}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();
this.a.connect(a)}P(){return this.l}X(a,b,d,h){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[4]=b,this.m(this.b.gain,b,d,h),this.m(this.a.gain,1-b,d,h)}}};self.me=class extends f{constructor(a,b,d,h,m,p){super(a);this.R="compressor";this.g=[b,d,h,m,p];this.h=this.f.createDynamicsCompressor();this.h.threshold.value=b;this.h.knee.value=d;this.h.ratio.value=h;this.h.attack.value=m;this.h.release.value=p}c(){this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(){}};
self.le=class extends f{constructor(a,b,d){super(a);this.R="analyser";this.g=[b,d];this.h=this.f.createAnalyser();this.h.fftSize=b;this.h.smoothingTimeConstant=d;this.Sd=new Float32Array(this.h.frequencyBinCount);this.ee=new Uint8Array(b);this.ce=this.Na=0;this.i.Ve(this)}c(){this.i.cg(this);this.h.disconnect();super.c()}va(){this.h.getFloatFrequencyData(this.Sd);this.h.getByteTimeDomainData(this.ee);const a=this.h.fftSize;let b=this.Na=0;for(var d=0;d<a;++d){let h=(this.ee[d]-128)/128;0>h&&(h=-h);
this.Na<h&&(this.Na=h);b+=h*h}d=self.da.Le;this.Na=d(this.Na);this.ce=d(Math.sqrt(b/a))}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(){}Fe(){return{tag:this.Y,index:this.Ud,peak:this.Na,rms:this.ce,binCount:this.h.frequencyBinCount,freqBins:this.Sd}}}}"use strict";
self.fa.Da(class extends self.sa{constructor(f){super(f,"mouse");I(this,[["cursor",a=>{document.documentElement.style.cursor=a}],["request-pointer-lock",()=>{this.v.G.requestPointerLock()}],["release-pointer-lock",()=>{document.exitPointerLock()}]]);document.addEventListener("pointerlockchange",()=>{u(this,"pointer-lock-change",{"has-pointer-lock":!!document.pointerLockElement})});document.addEventListener("pointerlockerror",()=>{u(this,"pointer-lock-error",{"has-pointer-lock":!!document.pointerLockElement})})}});
